### ISSUE TITLE
Optimize for layer caching during init

### ISSUE THREAD

**Issue by carolynvs** [getporter/terraform-mixin#73]
As part of mixin's build, we output the following lines, so that the invocation image has the providers installed. The problem with this is that any time that you change anything in the bundle, whether or not it's related to terraform, init is run again and the layer cache is invalidated. When a small bundle clocks in at 1.6GB this is a problem.

```Dockerfile
COPY . $BUNDLE_DIR
RUN cd %s && terraform init -backend=false
```

What if we encouraged people to put their provider declarations into a separate file, e.g. providers.tf, and then only copied that file into the bundle before running init? The rest is copied into the bundle later when we copy the bundle contents.

```yaml
mixins:
  - terraform:
      initFile: terraform/providers.tf # they could put anything here and we will use it in the dockerfile
```
