### ISSUE TITLE
Make the working directory configurable per command

### ISSUE THREAD

**Issue by carolynvs** [getporter/terraform-mixin#81]
I recently added working directory as a mixin level config, which lets the user override the default directory with all their terraform files. #61 Sometimes people have multiple terraform modules though, and its not possible to use more than one in the same bundle. We should add working directory to the terraform mixin command so that you can do something like this:

```yaml
install:
  - terraform:
       workingDir: mymodule1
  - terraform:
       workingDir: mymodule2
```

**Comment by RunCor399** [comment]
Hi @carolynvs, I've noticed that right now the mixin defaults to "terraform" dir even though a specific working directory is set up in the same way as explained in the docs. Is there a reason for this behaviour?

**Comment by bdegeeter** [comment]
We should consider using terraform's `-chdir` to solve this instead of `cd <workingDir> && terraform`

**Comment by sgettys** [comment]
Need to have the mixin config accept multiple workingDirs as well:
```
mixins:
  - terraform:
       workingDirs:
         - mymodule1
         - mymodule2
```

**Comment by sgettys** [comment]
Also need to figure out the case at the action level:
```
mixins:
  - terraform:
       workingDirs:
         - mymodule1
         - mymodule2
install
  - terraform:
       workingDir: "mymodule1"
  - terraform:
       workingDir: "mymodule2"
```

**Comment by sgettys** [comment]
Logic to support this would need to be able to mutually exclusively set "workingDir" or "workingDirs" at the mixin level so that the terraform can be built into the bundle. And then require at the action level if "workingDirs" is set that each terraform action requires one of the values set in the mixin config.

**Comment by RunCor399** [comment]
> Also need to figure out the case at the action level:
> 
> ```
> mixins:
>   - terraform:
>        workingDirs:
>          - mymodule1
>          - mymodule2
> install
>   - terraform:
>        workingDir: "mymodule1"
>   - terraform:
>        workingDir: "mymodule2"
> ```

Wouldn't it be enough to specify at the mixin level a boolean to enable "multipleWorkingDir", and then specify each of these working directories at the step level?

```
mixins:
    - terraform:
         multipleWorkingDir: true

install
    - terraform:
          workingDir: "mymodule1" 
    - terraform:
          workingDir: "mymodule2" 
```

Of course mutual exclusion between **workingDir** and **multipleWorkingDir**  at the mixin level should be kept in consideration
