### ISSUE TITLE
Allow saving output immediately as a file

### ISSUE THREAD

**Issue by carolynvs** [getporter/terraform-mixin#84]
In some cases I need to use an output immediately as a file, for example:

1. run terraform to create a kubernetes cluster
2. run helm to install a release on that cluster.

To do this without fussing with the exec mixin, the terraform outputs should be able to be sent to a file like so:

```
install:
  - terraform:
      description: "Create infrastructure"
      vars:
        installation: "{{ installation.name}}"
        location: "{{ bundle.parameters.location }}"
      outputs:
        - name: connstr
        - name: kubeconfig
          destinationFile: /root/.kube/config
```
